version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-grpc-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lkitb51qpe5f"
s3_prefix = "aws-sam-grpc-sample"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SsmPath=\"/dev/aws-sam-grpc-sample/dotenv\""
