AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-grpc-sample

Parameters:
  SsmPath:
    Type: String
    Default: /dev/aws-sam-grpc-sample/dotenv
    Description: ssm prameter key path for dotenv body

Globals:
  Function:
    Timeout: 5

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: entrypoint/api
      Handler: api
      Runtime: go1.x
      Tracing: Active
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          SSM_PATH: !Ref SsmPath
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonCognitoPowerUser
        - AmazonSSMReadOnlyAccess

  BatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: entrypoint/batch
      Handler: batch
      Runtime: go1.x
      Tracing: Active
      Events:
        RunBatch:
          Type: Schedule
          Properties:
            Description: ""
            Enabled: !If [ShouldPreventRunBatch, false, true]
            Input: '{"args":["command-name-lambda"]}'
            Schedule: "cron(0/5 * * * ? *)"
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Environment:
        Variables:
          SSM_PATH: !Ref SsmPath
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonCognitoPowerUser
        - AmazonSSMReadOnlyAccess

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: default
      BinaryMediaTypes:
        - "*/*"
