AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-grpc-sample

Parameters:
  SsmPath:
    Type: String
    Default: /dev/aws-sam-grpc-sample
    Description: ssm prameter key path for dotenv body

Globals:
  Function:
    Timeout: 5

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: hello-world
      Runtime: go1.x
      Tracing: Active
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          SSM_PATH: !Ref SsmPath
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSSMReadOnlyAccess

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: default
      BinaryMediaTypes:
        - "*/*"